export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';

export const INIT_FIREBASE_AUTH = 'INIT_FIREBASE_AUTH';

export const RETRIEVE_ACCOUNT_START = 'RETRIEVE_ACCOUNT_START';
export const RETRIEVE_ACCOUNT_FAILED = 'RETRIEVE_ACCOUNT_FAILED';
export const RETRIEVE_ACCOUNT_SUCCESS = 'RETRIEVE_ACCOUNT_SUCCESS';

export const UPDATE_ACCOUNT_START = 'UPDATE_ACCOUNT_START';
export const UPDATE_ACCOUNT_FAILED = 'UPDATE_ACCOUNT_FAILED';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';

export const RETRIEVE_VENDORS_START = 'RETRIEVE_VENDORS_START';
export const RETRIEVE_VENDORS_FAILED = 'RETRIEVE_VENDORS_FAILED';
export const RETRIEVE_VENDORS_SUCCESS = 'RETRIEVE_VENDORS_SUCCESS';